### ISSUE TITLE
Android 11. Cant share a file from a Android 11 device.

### ISSUE THREAD

**Issue by JonasLykkeIOspect** [FinanzRitter/nativescript-share-file#4]
### Which platform(s) does your issue occur on?
- Android 11 (Android API 30)

### Please, provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it):
- 7.2.0

- Plugin(s): (look for the version numbers in the `package.json` file of your
project and paste your dependencies and devDependencies here):
  "dependencies": {
    "@angular/animations": "~11.2.0",
    "@angular/common": "~11.2.0",
    "@angular/compiler": "~11.2.0",
    "@angular/core": "~11.2.0",
    "@angular/forms": "~11.2.0",
    "@angular/platform-browser": "~11.2.0",
    "@angular/platform-browser-dynamic": "~11.2.0",
    "@angular/router": "~11.2.0",
    "@danvick/ngx-translate-nativescript-loader": "^3.0.0",
    "@finanzritter/nativescript-pdf-view": "^3.0.3",
    "@finanzritter/nativescript-share-file": "^2.0.0",
    "@nativescript-community/drawingpad": "^4.1.0",
    "@nativescript-community/ui-material-button": "^5.2.5",
    "@nativescript-community/ui-material-cardview": "^5.2.5",
    "@nativescript-community/ui-material-dialogs": "^5.2.6",
    "@nativescript-community/ui-material-floatingactionbutton": "^5.2.5",
    "@nativescript-community/ui-material-slider": "^5.2.5",
    "@nativescript-community/ui-material-textfield": "^5.2.6",
    "@nativescript-community/ui-material-textview": "^5.2.6",
    "@nativescript/angular": "~11.0.1",
    "@nativescript/appversion": "^2.0.0",
    "@nativescript/camera": "^5.0.8",
    "@nativescript/core": "~7.2.1",
    "@nativescript/datetimepicker": "^2.0.4",
    "@nativescript/email": "^2.0.2",
    "@nativescript/firebase": "^11.1.3",
    "@nativescript/imagepicker": "^1.0.2",
    "@nativescript/local-notifications": "^5.1.0",
    "@nativescript/theme": "~3.0.1",
    "@ngx-translate/core": "^13.0.0",
    "@nstudio/nativescript-loading-indicator": "^4.0.0",
    "jspdf": "^2.3.0",
    "jspdf-autotable": "^3.5.14",
    "nativescript-app-tour-updated": "^2.0.2",
    "nativescript-couchbase-plugin": "^0.9.6",
    "nativescript-fancyalert": "^3.0.9",
    "nativescript-photo-editor-with-fixed-textfield": "^61.1.0",
    "nativescript-printer": "^2.0.0",
    "nativescript-purchase": "^2.0.14",
    "nativescript-ui-listview": "^9.1.0",
    "nativescript-ui-sidedrawer": "~9.0.3",
    "reflect-metadata": "~0.1.13",
    "rxjs": "^6.6.3",
    "zone.js": "~0.11.3"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~11.2.0",
    "@nativescript/android": "7.0.1",
    "@nativescript/ios": "7.2.0",
    "@nativescript/webpack": "~4.1.0",
    "@ngtools/webpack": "~11.1.1",
    "codelyzer": "~6.0.1",
    "node-sass": "^4.14.1",
    "tslint": "~6.1.3",
    "typescript": "~4.0.5"
  },

### Please, tell us how to recreate the issue in as much detail as possible. 
I'm trying to share a generated PDF file. Works with Android 10 and lower. But not on 11. Works on iOS also.
Tried https://github.com/nativescript-community/ui-share-file, same issue. And they dossent support reporting an issue. 
The forked repo this plugin is build on, did a PR yestoday with a fix https://github.com/braune-digital/nativescript-share-file/pull/16 ... But they didnt make a new release, and I have tried to manuelt write the code to match theirs to your plugin. But I dit not get it to work ether :/ Keept saying "share intent failed"

**Comment by sc85** [comment]
Took me a while but finally had a look and added the changes done by @interrobrian. A new release is available as version v2.0.1 on npm.
@interrobrian Thanks for the PR to https://github.com/braune-digital/nativescript-share-file/pull/16 . I also added you to contributors of this repo. I hope that's alright for you.
