### ISSUE TITLE
ShareFile: Android intent failed

### ISSUE THREAD

**Issue by cristiandaulisio** [FinanzRitter/nativescript-share-file#5]
Hello, i am using the 2.0.1 version.
Android 9
I follow the instruction with fileprovider.

when i try to share a file i receive :
ShareFile: Android intent failed

**Comment by sc85** [comment]
Hey, just had a quick check with the demo app on Android 11 (real device) and Android 9 (real device + emulator). No crashes on any of them.
Have you tried the demo app? Which nativescript version do you use? I am using v8.1.5.
```
ns --version
> 8.1.5
```

**Comment by cristiandaulisio** [comment]
Hello sc85.
![immagine](https://user-images.githubusercontent.com/29864737/151325404-6de3d3a1-1c65-41fe-9f99-352680b6c0e4.png)

this is the code i am using:
` try
            {
                const shareFile = new ShareFile();

                shareFile.open({
                    path: file.path,
                    intentTitle:  "Apri il file con...", // optional Android
                    rect: { // optional iPad
                        x: 110,
                        y: 110,
                        width: 0,
                        height: 0
                    },
                    options: true, // optional iOS
                    animated: true // optional iOS
                });
            
            }
            catch (err)
            {
                console.log(err)
            }`

**Comment by sc85** [comment]
Have you tried if the demo app is working at all for you?
1. Clone the repo
2. Go to nativescript-share-file/demo
3. Run `npm i`
4. Run `ns platform add android`
5. Go to nativescrit-share-file/src
6. run `npm run demo.android`

Furthermore, have you added the FileProvider part to the `AndroidManifest.xml` of your app? If you copy the stuff from the demo, then don't forget to also add the `file_paths.xml` (see `App_Resources\Android\src\main\res\xml\file_paths.xml`).

**Comment by cristiandaulisio** [comment]
Hello, i am trying your instruction but i receive this error:

Execution failed for task ':app:javaPreCompileDebug'.
duplicate entry: META-INF/LICENSE.txt

Well i insert a console.log in your code and i have:
JS: Error: java.lang.IllegalArgumentException: Couldn't find meta-data for provider with authority <packagename>.fileprovider

My fileprovider is:
`<?xml version="1.0" encoding="utf-8" ?>
<paths xmlns:android="http://schemas.android.com/apk/res/android">
    <external-path name="external_files" path="." />
    <files-path name="file" path="/" />
    <external-files-path name="external_files" path="." />
    <cache-path name="cache" path="." />
    <external-cache-path name="external_cache" path="." />
</paths>`

and my manifest is:
`<provider
		android:name="androidx.core.content.FileProvider" 
		android:authorities="<packagenamehere>.provider"
		 android:exported="false" 
		 android:grantUriPermissions="true">
		 <meta-data  tools:replace="android:resource"
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/provider_paths"/>
		</provider>`

**Comment by cristiandaulisio** [comment]
Ok the problem was 
android:authorities="${applicationId}.fileprovider"

my manifest was
android:authorities="${applicationId}.provider"

i need to add "tools:replace="android:authorities"" too because i was receiving merge error..

**Comment by sc85** [comment]
Hi @Atomico001, does this mean the issue is solved for you?

**Comment by cristiandaulisio** [comment]
Yes Thanks,
